spring:
  application:
    name: spring-boot-das-trincheiras
#  virtual threads
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  #  platform threads
  tomcat:
    threads:
      max: 20
logging:
  level:
    dev.valente: debug
#  file:
#    name: logs/minha-aplicacao.log
#    path: logs