spring:
  application:
    name: spring-boot-das-trincheiras
  #  virtual threads
  threads:
    virtual:
      enabled: true
  profiles:
    active: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    password: valente

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  #  platform threads
  tomcat:
    threads:
      max: 20
logging:
  level:
    dev.valente: debug
    org.springframework.security: debug


#  file:
#    name: logs/minha-aplicacao.log
#    path: logs

database:
  username: ${LOCAL_USERNAME:joaquin}
  password: ${LOCAL_PASSWORD:3030}
  url: ${LOCAL_URL:localhost:3203}