spring:
  application:
    name: spring-boot-das-trincheiras
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /

  error:
    include-stacktrace: on_param

  tomcat:
    threads:
      max: 20