spring:
  application:
    name: spring-boot-das-trincheiras
  #  virtual threads
  threads:
    virtual:
      enabled: true
  profiles:
    active: mysql

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  #  platform threads
  tomcat:
    threads:
      max: 20
logging:
  level:
    dev.valente: debug
#  file:
#    name: logs/minha-aplicacao.log
#    path: logs

database:
  username: ${LOCAL_USERNAME:joaquin}
  password: ${LOCAL_PASSWORD:3030}
  url: ${LOCAL_URL:localhost:3203}